/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.bandocongnghe.view;

import java.awt.Color;
import java.io.File;
import java.nio.file.Paths;
import java.sql.Date;
import java.util.List;
import javax.swing.JFileChooser;
import poly.bandocongnghe.Controller.SignupfofanaccountController;
import poly.bandocongnghe.dao.UserDAO;
import poly.bandocongnghe.dao.User_detailDAO;
import poly.bandocongnghe.dao.impl.UserDAOImpl;
import poly.bandocongnghe.dao.impl.User_detailDAOImpl;
import poly.bandocongnghe.entity.User;
import poly.bandocongnghe.entity.User_detail;
import poly.bandocongnghe.util.XDialog;
import poly.bandocongnghe.util.XIcon;

/**
 *
 * @author lam
 */
public class SignupfofanaccountJDialog extends javax.swing.JDialog implements SignupfofanaccountController{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignupfofanaccountJDialog.class.getName());
    
     UserDAO daouser = new UserDAOImpl();
    List<User> itemsuser = List.of();
    List<User_detail> item =List.of();
    User_detailDAO dao =new User_detailDAOImpl();
    private  String pathanh; 
    /**
     * Creates new form SignupfofanaccountJDialog
     */
    public SignupfofanaccountJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    public  User_detail getform(){
        User_detail enti=new User_detail();
        enti.setAddress(txtAddress.getText());
        enti.setDob(Date.valueOf(txtDob.getText()));
        enti.setFullname(txtfullname.getText());
        enti.setGender(rbtnam.isSelected()?"nam":"nu");
        enti.setPhone(txtphone.getText());
        enti.setPhoto(pathanh);
        enti.setUsername(txtusername.getText());
        return enti; 
    }
    public  User  getformuser(){
        User enti=new User();
        enti.setEmail(txtemail.getText());
        enti.setPassword(txtpassword.getText());
        enti.setRoles(3);
        enti.setOtp("");
        enti.setStatus(1);
        enti.setUsername(txtusername.getText());
       
        return enti; 
    }
public  void Signup(){
User_detail enti=this.getform();
    User enti1=this.getformuser();
    daouser.create(enti1);
dao.create(enti);
    XDialog.alert("thêm thành công");
    clear();
}
public  void clear(){
txtAddress.setText("");
txtDob.setText("");
txtfullname.setText("");
txtpassword.setText("");
txtpasswordcom.setText("");
txtphone.setText("");
txtusername.setText("");
buttonGroupgender.clearSelection();
txtemail.setText("");
pathanh="";
XIcon.XIconebylam(jlabelphoto, pathanh);
}
public void chonanh() {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("chon anh");
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Ảnh (JPG, PNG, JPEG)", "jpg", "png", "jpeg"));
        chooser.setCurrentDirectory(new File("src/main/resources/photo"));

        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String imagepatch = Paths.get(file.getAbsolutePath()).getFileName().toString();

            pathanh = imagepatch;
            System.out.println("link:" + pathanh);
            XIcon.XIconebylam(jlabelphoto , pathanh);
//    
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupgender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        buttonthunho = new javax.swing.JButton();
        buttonx = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpasswordcom = new javax.swing.JPasswordField();
        txtpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnSignup = new javax.swing.JButton();
        txtphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtfullname = new javax.swing.JTextField();
        rbtnam = new javax.swing.JRadioButton();
        rbtnu = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlabelphoto = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtDob = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonthunho.setBackground(new java.awt.Color(102, 255, 255));
        buttonthunho.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        buttonthunho.setForeground(new java.awt.Color(51, 51, 255));
        buttonthunho.setText("-");
        buttonthunho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonthunhoMouseClicked(evt);
            }
        });
        jPanel1.add(buttonthunho, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 50, 30));

        buttonx.setBackground(new java.awt.Color(102, 255, 255));
        buttonx.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonx.setText("X");
        buttonx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonxMouseExited(evt);
            }
        });
        jPanel1.add(buttonx, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 70, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ĐĂNG KÝ TÀI KHOẢN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 260, 80));

        jLabel2.setText("Nhập Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel3.setText("Nhập password mới");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 350, -1));
        jPanel1.add(txtpasswordcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 340, -1));
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 350, -1));

        jLabel4.setText("Nhâp lại mật khẩu");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        jCheckBox1.setText("Hiện mật khẩu");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jCheckBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCheckBox1PropertyChange(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel5.setText("Nhập Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 340, -1));

        btnSignup.setText("Đăng ký");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, -1, -1));

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 340, -1));

        jLabel6.setText("Nhập tên đầy đủ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jLabel7.setText("Nhập số điệ thoại");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));
        jPanel1.add(txtfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 350, -1));

        buttonGroupgender.add(rbtnam);
        rbtnam.setText("Nam");
        jPanel1.add(rbtnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        buttonGroupgender.add(rbtnu);
        rbtnu.setText("Nữ");
        jPanel1.add(rbtnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jLabel8.setText("Chọn giới tính");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        jLabel9.setText("Nhập địa chỉ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 340, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelphoto, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelphoto, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, 290));

        jButton2.setText("Chọn ảnh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));
        jPanel1.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 210, -1));

        jLabel10.setText("Nhập ngày -Tháng-Năm sinh theo định dạng yyyy-mm-dd");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 320, -1));

        jButton3.setText("Trở lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, -1));

        jButton1.setText("Nhâp mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonthunhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonthunhoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_buttonthunhoMouseClicked

    private void buttonxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonxMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonxMouseClicked

    private void buttonxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonxMouseEntered
        buttonx.setBackground(Color.BLUE); // TODO add your handbuleling code here:
    }//GEN-LAST:event_buttonxMouseEntered

    private void buttonxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonxMouseExited
        // TODO add your handling code here:
        buttonx.setBackground(Color.GREEN);
    }//GEN-LAST:event_buttonxMouseExited

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            // jCheckBox1.setBorderPaintedFlat(true);
            jCheckBox1.setText("ẩn mật khẩu");
            txtpassword.setEchoChar((char)0);
        txtpasswordcom.setEchoChar((char)0);
        }else {jCheckBox1.setText("hiện mât khẩu");
            txtpassword.setEchoChar('*');
            txtpasswordcom.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCheckBox1PropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jCheckBox1PropertyChange

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        Signup();
    }//GEN-LAST:event_btnSignupActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        chonanh();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SignupfofanaccountJDialog dialog = new SignupfofanaccountJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignup;
    private javax.swing.ButtonGroup buttonGroupgender;
    private javax.swing.JButton buttonthunho;
    private javax.swing.JButton buttonx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabelphoto;
    private javax.swing.JRadioButton rbtnam;
    private javax.swing.JRadioButton rbtnu;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfullname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JPasswordField txtpasswordcom;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
