/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.bandocongnghe.view;

import java.awt.Color;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Pattern;
import poly.bandocongnghe.dao.UserDAO;
import poly.bandocongnghe.dao.impl.UserDAOImpl;
import poly.bandocongnghe.entity.User;
import poly.bandocongnghe.util.EmailSender;
import poly.bandocongnghe.util.OTPGenerator;
import poly.bandocongnghe.util.XDialog;

/**
 *
 * @author lam
 */
public class ForgotpasswordJdialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotpasswordJdialog.class.getName());
    UserDAO dao = new UserDAOImpl();
    List<User> items = List.of();
    int a=0;
//    @Autowired
  //  private EmailService emailService;
    /**
     * Creates new form ForgotpasswordJdialog
     */
    
     private EmailSender emailService;
     
    /**
     * Creates new form ForgotpasswordJdialog
     */
    public ForgotpasswordJdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      setLocationRelativeTo(null);
        btdoimk.setEnabled(false);
    // ApplicationContext context = new AnnotationConfigApplicationContext(KaraokeApplication.class);
       // emailService = context.getBean(EmailSender.class);
       emailService = new EmailSender(); 
    }
    private String otp=null;
    private String email1=null;
    private String username=null;
    
    private  void xacnhanmaoip(){
      User  items= dao.findById(username);
        if(items==null){XDialog.alert("username sai");}else{
       
       otp= items.getOtp();
      
        
    if(txtnhapmaotp.getText().equals(otp)){
    btdoimk.setEnabled(true);
    a=1;
    }else{
    XDialog.alert("nhap sai otp hoặc sai username");
    }}
    }
private void clikknhanopt(){
    
    otp=OTPGenerator.generateOTP(6);
    
    btnhanotp.setEnabled(false);
//    EmailService gui =new EmailService();
  a=0;
  
if (emailService == null) {
    throw new IllegalStateException("emailService chưa được khởi tạo! Kiểm tra cấu hình.");
}
username=txtusername.getText();
 email1=txtemail.getText();
User items= dao.findById(username);
        if(items==null){XDialog.alert("username sai");
        btnhanotp.setEnabled(true);
        }else{
User us=new User();
us.setOtp(otp);
us.setUsername(username);
    try {
       dao.updateotp(us); 
    } catch (Exception e) {
        XDialog.alert("sai username");
    }


    try {
        emailService.sendEmail(email1," Ma OTP :", otp);
    } catch (Exception e) {
        XDialog.alert("sai email");
    }
  //emailService.sendEmail("ln678090@gmail.com", "743859");
        XDialog.alert("Đẫ gửi mã code");
       
        
         Timer timer = new Timer();
    timer.schedule(new TimerTask() {
        @Override
        public void run() {
 if(a==0){
          otp =null;
          User us=new User();
us.setOtp("");
us.setUsername(username);
dao.updateotp(us);
          
          XDialog.alert("maotp het hạn");
          btnhanotp.setEnabled(true);
        }
        }
    }, 1*60*1000);
       
    
    
    
        }}

private User getForm(){
 User entity = new User();
 entity.setUsername(txtemail.getText());
 entity.setPassword(txtxacnhanmk.getText());
 return  entity;
}
private void doimk(){
if(txtpasswordnew.getText().equals(txtxacnhanmk.getText())){
 User entity = this.getForm();
        dao.updatepass(entity);
        XDialog.alert("da doi mk");
        btdoimk.setEnabled(false);
}else{
XDialog.alert("nhap lại mật khẩu không khớp");
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtemail = new javax.swing.JTextPane();
        btxacnhanmaotp = new javax.swing.JButton();
        btdoimk = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtnhapmaotp = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtusername = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtpasswordnew = new javax.swing.JPasswordField();
        btnhanotp = new javax.swing.JButton();
        txtxacnhanmk = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonthunho = new javax.swing.JButton();
        buttonx = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jScrollPane1.setViewportView(txtemail);

        btxacnhanmaotp.setText("Xác nhận mã OTP");
        btxacnhanmaotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxacnhanmaotpActionPerformed(evt);
            }
        });

        btdoimk.setText("Đổi mật khẩu");
        btdoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdoimkActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(txtnhapmaotp);

        jScrollPane2.setViewportView(txtusername);

        jLabel1.setText("Nhập Email");

        jLabel5.setText("Nhập username");

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("làm mới");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnhanotp.setText("Nhận mã OTP");
        btnhanotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhanotpActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập mã OTP");

        jLabel3.setText("Nhập mật mới");

        jLabel4.setText("Nhập lại mật khảu");

        buttonthunho.setBackground(new java.awt.Color(102, 255, 255));
        buttonthunho.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        buttonthunho.setForeground(new java.awt.Color(51, 51, 255));
        buttonthunho.setText("-");
        buttonthunho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonthunhoMouseClicked(evt);
            }
        });

        buttonx.setBackground(new java.awt.Color(102, 255, 255));
        buttonx.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonx.setText("X");
        buttonx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonxMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trump.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(735, Short.MAX_VALUE)
                        .addComponent(buttonthunho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btxacnhanmaotp)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtxacnhanmk, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpasswordnew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnhanotp))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btdoimk, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(19, 19, 19)))))
                .addGap(2, 2, 2)
                .addComponent(buttonx, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonthunho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhanotp))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btxacnhanmaotp)
                                .addComponent(jButton2)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(txtpasswordnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtxacnhanmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btdoimk))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(51, 51, 51))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btxacnhanmaotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxacnhanmaotpActionPerformed
        // TODO add your handling code here:

        if(!txtnhapmaotp.getText().isEmpty()){
            xacnhanmaoip();
        }else {XDialog.alert("chưa nhập otp");}
    }//GEN-LAST:event_btxacnhanmaotpActionPerformed

    private void btdoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdoimkActionPerformed
        // TODO add your handling code here:

        if(!txtpasswordnew.getText().isEmpty() || !txtxacnhanmk.getText().isEmpty()){
            if(txtpasswordnew.getText().length()>7||txtxacnhanmk.getText().length()>7){
                doimk();
            }else{XDialog.alert("mật khẩu phải từ 8 ký tự trở lên");}
        }else {XDialog.alert("chưa nhập mật khảu cần đổi");}
    }//GEN-LAST:event_btdoimkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnhanotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhanotpActionPerformed
        // TODO add your handling code here:\
        if(!txtemail.getText().isEmpty()&&!txtusername.getText().isEmpty()){
            boolean check=Pattern.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$", txtemail.getText());
            if(check){
                clikknhanopt();
            }else {XDialog.alert("email chưa đúng dạng");}
        }else {XDialog.alert("chưa nhập email hoặc username");}
    }//GEN-LAST:event_btnhanotpActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened

    private void buttonthunhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonthunhoMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_buttonthunhoMouseClicked

    private void buttonxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonxMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonxMouseClicked

    private void buttonxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonxMouseEntered
        buttonx.setBackground(Color.blue); // TODO add your handbuleling code here:
    }//GEN-LAST:event_buttonxMouseEntered

    private void buttonxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonxMouseExited
        // TODO add your handling code here:
        buttonx.setBackground(Color.GREEN);
    }//GEN-LAST:event_buttonxMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        otp=null;
        username=null;
        email1=null;
        btnhanotp.setEnabled(true);
        a=1;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ForgotpasswordJdialog dialog = new ForgotpasswordJdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdoimk;
    private javax.swing.JButton btnhanotp;
    private javax.swing.JButton btxacnhanmaotp;
    private javax.swing.JButton buttonthunho;
    private javax.swing.JButton buttonx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane txtemail;
    private javax.swing.JTextPane txtnhapmaotp;
    private javax.swing.JPasswordField txtpasswordnew;
    private javax.swing.JTextPane txtusername;
    private javax.swing.JPasswordField txtxacnhanmk;
    // End of variables declaration//GEN-END:variables
}
